language: scala
scala:
   - 2.13.1

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot"

jdk:
  - oraclejdk12

script:
  - sbt clean scalafmtCheck scalafmtSbtCheck coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
